### ISSUE TITLE
Vertical align for image flags in the navbar

### ISSUE THREAD

**Issue by Galixte** [alg5/quicklanguage#14]
Hi @alg5,

could you make in sort to make a vertical align for the image flags in the navbar: http://www.ezcom-fr.com/download/file.php?id=307.

**Comment by Galixte** [comment]
Fix proposed here: https://github.com/alg5/quicklanguage/pull/15.

**Comment by alg5** [comment]
yes, sure

**Comment by Galixte** [comment]
thanks ;)
