### ISSUE TITLE
Sort by name the language names in box on viewtopic

### ISSUE THREAD

**Issue by Galixte** [alg5/quicklanguage#16]
Hi,

could you make in sort to orderer the list of languages in box on viewtopic. Maybe the Yandex API allow that.

**Comment by alg5** [comment]
Hi, Galixte, I get sorted list from yandex, I see it/ And what about you?

**Comment by Galixte** [comment]
Hi @alg5,

not for me, it's completly shuffle.

**Comment by alg5** [comment]
hmm
I'd checked: Yandex API haven't option sort, but I get sorted list of langs

**Comment by Galixte** [comment]
Thanks ;)
