### ISSUE TITLE
Easter egg functionality with a language key

### ISSUE THREAD

**Issue by Galixte** [alg5/quicklanguage#26]
Hi @alg,

On my french board (french language by default), with the language key in english `'SITE_DESCRIPTION_NAME'    => 'Site description',``if i personalize this language key for english users it’s not translated whereas the other language keys in english are correctly translated.

**Comment by alg5** [comment]
I checked this. Default forum lang is Russian, I added in english keys row 'SITE_DESCRIPTION_NAME' => 'Site description',, when I switch lang on English I get this description

**Comment by alg** [comment]
Do me a favor, @Galixte. Stop using @alg, it's @alg5. :)

**Comment by Galixte** [comment]
Sorry alg. ;)

**Comment by Galixte** [comment]
@alg5, strange i will do again m'y tests...

**Comment by alg5** [comment]
@alg  it's five!!! :)
