### ISSUE TITLE
Translate functionalily

### ISSUE THREAD

**Issue by Galixte** [alg5/quicklanguage#6]
Hi,

this functionality doesn't work. When i click on it nothing happens.

My key begins by:

```
trnsl.1.1.20150407T072912Z.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by alg5** [comment]
You key look like valid
May be firebug shows some errors?
you can test this option here: http://chugunok.net/forum_test_3_1/viewtopic.php?f=28&t=6193

**Comment by alg5** [comment]
if you want to write some text, please enter with account
tester
12345

**Comment by Galixte** [comment]
Hi,

Yes on your forum it's OK. 

On my forum i don't have the menu box under the messages permitting to choose the language that i want. I have only the "Translate" link and when i click on it, it's replaced with "Show original text" link without translation of the message text.

I have tested on local environment with Quickinstall (phpBB vanilla 3.1.3) and Debug activated and i have this information in ACP => extension => Quicklanguage settings page:

```
[phpBB Debug] PHP Notice: in file [ROOT]/ext/alg/quicklanguage/acp/acp_quicklanguage_module.php on line 100: Undefined index: ACP_QUICKREPLY
[phpBB Debug] PHP Notice: in file [ROOT]/ext/alg/quicklanguage/acp/acp_quicklanguage_module.php on line 101: Undefined index: ACP_QUICKREPLY_EXPLAIN
```

It is possible that the API Yandex works only with website which are in particular geographic zone like ru zone ? (my online forum is in French place)

**Comment by alg5** [comment]
"Undefined index: ACP_QUICKREPLY...ACP_QUICKREPLY_EXPLAIN"
Sorry. it's my mistake
please, in file acp_quicklanguage_module.php find line 40 and replace ACP_QUICKREPLY on ACP_QUICK_LANGUAGE

**Comment by alg5** [comment]
"On my forum i don't have the menu box under the messages permitting to choose the language that i want. I have only the "Translate" link and when i click on it, it's replaced with "Show original text" link without translation of the message text."
I didn't update github yet, so option to choose the language now exist only my test forum. For your forum you must set on firebug ( tab network) and check returned data

"It is possible that the API Yandex works only with website which are in particular geographic zone like ru zone ? (my online forum is in French place)"
I sure that it is possible for all over the world, My forum placed in USA geographic zone and I live not in Russia

**Comment by Galixte** [comment]
OK it works if the next conditions are presents:
- the user has to use english language by default
- the text isn't between QUOTE tags.

Could fixe those ?
- extend the translation to all languages used by users
- it works with text between QUOTE tags

**Comment by alg5** [comment]
1. yes
2. I'll think

**Comment by alg5** [comment]
done
please. change message "translate" on "translate to" in the file language/fr/quicklanguage.php

**Comment by Galixte** [comment]
Hi,

it's done here: https://github.com/alg5/quicklanguage/pull/8

Thanks, the extension works with a lot of different types of messages.

**Comment by alg5** [comment]
all merged
Galixte. thanks for your cooperation
